### ISSUE TITLE
Question on non-energy use in Final Energy|Industry

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#103]
Dear colleagues,
the NAVIGATE template defined:

- `Final Energy` as "total final energy consumption by all end-use sectors and all fuels, excluding transmission/distribution losses, including non-energy use"
- `Final Energy|Industry` as "final energy consumed by the industrial sector, excluding non-energy use (e.g.feedstocks)"

The new [community template](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/variable/energy/final-energy.yaml#L68) seems to be not specific anymore about that. Should we add that, or is it intended that `Final Energy|Industry` also contains non-energy use? @IAMconsortium/common-defintions-energy

**Comment by danielhuppmann** [comment]
This is included in the sector-tag-list [here](https://github.com/IAMconsortium/common-definitions/blob/455f63a905ced69e7d14bac5443cf4b8bc72aced/definitions/variable/energy/tag_all_sectors.yaml#L4). You can double-check the expanded variable descriptions via the automatically generated xlsx file at https://files.ece.iiasa.ac.at/common-definitions/common-definitions-template.xlsx

**Comment by orichters** [comment]
Ah, thanks, I missed that. And yeah, I should have known about the xlsx file :)
