### ISSUE TITLE
description tag is not expanded in xlsx export

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#132]
description tag is not expanded in xlsx export

Example:
Final Energy|Non-Energy Use|Chemicals|Gases
EJ/yr
Final energy consumption of {Secondary Fuel} by the {Non-Energy Sector with Source} for non-combustion processes

https://github.com/IAMconsortium/common-definitions/blob/258c943fdbc16f362865367dba68daba50bcac93/definitions/variable/energy/final-energy.yaml#L26-L30

**Comment by danielhuppmann** [comment]
@dc-almeida & @phackstock, can you please check whether this is an issue in nomenclature?

**Comment by phackstock** [comment]
I'll take a look, my hunch is that we currently don't support substitution of multiple different tags.

**Comment by orichters** [comment]
For the variables it works, but not for the description, even if there is only one single tag:
- "Use of {Secondary Fuel} for carbon management by production of biochar using pyrolysis"
- "Use of {Secondary Fuel} for carbon management by direct air capture"
- "Use of {Secondary Fuel} for carbon management by electrochemical separation of dissolved inorganic carbon from seawater"

etc.

**Comment by orichters** [comment]
I think I got the problem. It is the use of a tag in the description that is not present in the variable name as well, see here:
https://github.com/IAMconsortium/common-definitions/blob/258c943fdbc16f362865367dba68daba50bcac93/definitions/variable/energy/final-energy.yaml#L120-L125

**Comment by phackstock** [comment]
Thanks for checking @orichters, I think we have to indeed open a nomenclature issue for that one.

**Comment by orichters** [comment]
In the sense that these errors are identified in the tests?

**Comment by phackstock** [comment]
In the sense that I think there's a bug here. A fix would of course also come with a test.

**Comment by phackstock** [comment]
Ah never mind, the tag replacement logic of nomenclature is sound after all. 
What we could check for is that all tags used in a variable need to occur in the name of the variable.

**Comment by phackstock** [comment]
Closing this issue as the non-replacement of the tags is expected and intended. 
If we would replace tags within a definitions that are not part of the name, we'd get duplicates.
