### ISSUE TITLE
Format of Region, Scenario names, Variable names and Descriptions

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#138]
I wonder whether it would make sense to define some standards for the naming of variables, model regions, scenario names and also descriptions.

- What characters are allowed in variables, units, descriptions etc.? Any rules? Any regular expression that must be matched?
- I would suggest to avoid `;` and `"` in descriptions, as they mess with the usual format PIK uses for exchange this data. It doesn't seem to be a big deal, but useful for us (there are a few uses of `"` which might be just removed [1](https://github.com/IAMconsortium/common-definitions/blob/38154572159d55517c5e61fc6bcdf8d77f530d6f/definitions/variable/energy/tag_secondary_energy_carriers_with_sources.yaml#L18), [2](https://github.com/IAMconsortium/common-definitions/blob/4f77be867cfa400c41ad826a64ad32e5b13d18ca/definitions/variable/energy/final-energy.yaml#L8), [3](https://github.com/IAMconsortium/common-definitions/blob/38154572159d55517c5e61fc6bcdf8d77f530d6f/definitions/variable/energy/tag_secondary_energy_carriers_with_sources.yaml#L71))
- Looking at a scenariomip csv snapshot, I wonder whether it would be preferable to avoid `,` in region names (not like [REMIND dies it](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/region/native_regions/REMIND_3.1.yml#L2)) such that the quoting of region names can be avoided, same for scenario names. I also would prefer not to have special characters in scenario names.

Might be worth thinking about it

**Comment by danielhuppmann** [comment]
Thanks for these suggestions - we have started to compile such guidelines at https://docs.ece.iiasa.ac.at/standards.html (rendered from a GitHub repo at https://github.com/iiasa/ece-docs) for lack of a better place. Feel free to open a PR there!

**Comment by danielhuppmann** [comment]
Follow-up (because I tried to implement this): Agree to make `;` and `"` *not recommended* but we will need double-quotes (at least) for list-comprehension, see for example
https://github.com/IAMconsortium/common-definitions/blob/cb857043274cadcf970d92c252e957594bdbdffe/definitions/region/native_regions/REMIND-MAgPIE_3.4-4.8.yml#L29

**Comment by orichters** [comment]
If we remove it from the descriptions, variables, scenario names and units, that would be a good step forward (or actually sufficient for the code I have in mind).
