### ISSUE TITLE
Final Energy Commercial Water

### ISSUE THREAD

**Issue by klau506** [IAMconsortium/common-definitions#212]
The following variables are present in the ScenarioMIP template:
```
Final Energy|Commercial|Water|Desalination
Final Energy|Commercial|Water|Groundwater Extraction
Final Energy|Commercial|Water|Surface Water Extraction
Final Energy|Commercial|Water|Transfer
```
but the `Water` pattern category is missing (`Final Energy|Commercial|Water`).

Might be worth adding it.

**Comment by danielhuppmann** [comment]
This variable will be added via #215
