### ISSUE TITLE
Emissions variable Domestic Aviation - add back in

### ISSUE THREAD

**Issue by jkikstra** [IAMconsortium/common-definitions#227]
Somehow, the Domestic Aviation emissions variable did not make it in the previous pull request. 

This was previously available under `Emissions|*|Energy|Demand|Transportation|Aviation`.

For clarity, I propose to reintroduce it as `Emissions|*|Energy|Demand|Transportation|**Domestic** Aviation` for clarity.

(thx @merfort for pinging me on this; @IAMconsortium/common-definitions-emissions )

**Comment by jkikstra** [comment]
OK, I see. 

But then this can only be on the global/international level, correct?

You only have global aviation? 
Does the regional 'Transportation' variable include or exclude emissions from domestic aviation?

**Comment by jkikstra** [comment]
Would it be an issue for you @merfort if we don't add that aggregate variable in the reporting template? 
See https://github.com/IAMconsortium/common-definitions/pull/228#issuecomment-2522490286 .

@danielhuppmann ; thing it, we will need to create it still for the CMIP7 harmonization anyhow, as we'll need to align with the CEDS variable.

**Comment by merfort** [comment]
Thanks! It is fine for now. I will come back to it later.

**Comment by danielhuppmann** [comment]
About reporting for international bunkers (emissions and fuel), these values are still available at national resolution, just not consistently counted to national statistics.

Whether a model represents international bunkers at the model-native regional resolution or only at global level is a different question.
