### ISSUE TITLE
Question on how template will be made available to modellers

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#24]
For REMIND-MAgPIE to prepare a submission, we need to read the template into `R`. We currently use [this function](https://github.com/pik-piam/piamInterfaces/blob/master/R/loadIIASATemplate.R) that can read `xlsx` files but also `yaml` files such as:
```
- Final Energy:
    unit: EJ/yr
```
But: It does not yet understand things such as:
```
- Emissions|{Tier-1 Species}:
-     unit: "{Tier-1 Species}"
```
How will the template be made available to modellers, such that we can prepare? Thanks!

**Comment by orichters** [comment]
Yes, as long as we somehow get an `R` object containing the full variable names out of it, we should be able to convert it into something our scripts understands.

**Comment by FlorianLeblancDr** [comment]
Hi Oliver, Daniel,
Do you know any equivalent of reticulate for python?

I am not sure the question was fully answered: wether each teams should use an appropriate script to convert the .yaml file to a full variable list,
Or if it is here on github that the community (we) should provide automatic conversion of the .yaml full (i-e, expanding the Tag on variables).

**Comment by danielhuppmann** [comment]
We now implemented a feature where the lists of variables and regions will be made available as an xlsx spreadsheet at https://files.ece.iiasa.ac.at/common-definitions/project-template.xlsx (and will be updated automatically to be in sync with the repository). The link to the file is already added to the Readme of this repository.

@orichters, is that sufficient for you?

**Comment by orichters** [comment]
Yes, that is perfect! [loadIIASATemplate](https://github.com/pik-piam/piamInterfaces/blob/master/R/loadIIASATemplate.R) happily read the file and we can figure out how we automate the download.

**Comment by orichters** [comment]
Will the min, max specification, summation rules etc. also be exported?

**Comment by danielhuppmann** [comment]
Yes, all attributes in the yaml are included as columns. We still need to come up with conventions on attribute-names for min/max-attributes, but that’s a different discussion…

**Comment by orichters** [comment]
Thanks, excellent!

**Comment by orichters** [comment]
There is another small issue: The expansion of the tags does not work yet in the `components` field:

![image](https://github.com/IAMconsortium/common-definitions/assets/90761609/03cf1d49-426d-4858-998f-5a8fc9597339)

**Comment by orichters** [comment]
Now at https://files.ece.iiasa.ac.at/common-definitions/common-definitions-template.xlsx
