### ISSUE TITLE
Role of international bunker emissions / global aggregates

### ISSUE THREAD

**Issue by orichters** [IAMconsortium/common-definitions#74]
Dear @IAMconsortium/common-definitions-emissions team,

I would be glad if you could decide about the treatment of international bunkers.

As far as I know, In the AR6 template, `Emissions|*` variables for `BC`, `CO`, `CO2`, `NOx`, `OC`, `Sulfur` and `VOC` had the international bunkers added only at the global level, leading to a situation that the sum over all regions did not match `World` results. In the NGFS project, we found out that the MESSAGE team also used this treatment for `Final Energy|Gases` and `Primary Energy|Gas`, while REMIND did it only for Emissions, and GCAM not at all. So there is definitely much room for confusion.

So I would be pleased if the variable description clarified how this should be treated. Thanks!

If I know that correctly, in NAVIGATE, the international bunkers were meant to be distributed to the regions, and I would propose to stick to that but make it explicit in the variable definition.

**Comment by danielhuppmann** [comment]
@volker-krey @strefler, please chime in here.

**Comment by strefler** [comment]
Yes, I think it makes sense to distribute the international bunkers (emissions and energy alike) to regions. If we don't do that, as Oliver noted the sum of regions will not equal the World total, and we still have emission and energy totals without bunkers if we need those values to compare to national inventories.

**Comment by orichters** [comment]
@volker-krey: An answer would be appreciated. We would like to "World = sum(regions)" for all variables in NGFS as well, and if we knew in the REMIND team that this is the future for the community template, that would make all our lives easier.

**Comment by byersiiasa** [comment]
Making explicit the bunkers and summing regions = World, makes sense to me, because otherwise this is the type of insider information that few people know, confuses others and makes it look like we can't sum...

**Comment by jkikstra** [comment]
Maybe less of a quick-fix, and I assume this has been discussed already before, but wouldn't the addition of a "Unassigned"/"Other"/"International" region make sense, for cases like international bunkers, such that {REGIONS}+UNASSIGNED = WORLD?

**Comment by danielhuppmann** [comment]
I like the idea of adding an "International" region. We already use "Other" for model-regions that cannot be mapped easily to the R5/R9/R10 regions, so I'd not use that for bunker emissions.

**Comment by jkikstra** [comment]
Yes, agreed. Should not use "Other" again.

Okay, would there be anything against introducing the "International" region?
